doctrine:
    dbal:
        driver: pdo_mysql
        server_version: '5.7'
        host: "%env(MYSQL_HOST)%"
        port: 3306
        user: "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASS)%"
        dbname: "%env(MYSQL_DB)%"
        types:
            uuid: App\Shared\DoctrineType\UuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Cinema:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/cinema'
                prefix: 'App\Cinema\Entity'
                alias: Cinema
            Schedule:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/schedule'
                prefix: 'App\Schedule\Domain'
                alias: Schedule
